apiVersion: skaffold/v2beta5
kind: Config
deploy:
  kubectl:
    manifests:
      - k8s.yaml
      - k8s-syncthing.yaml
      - k8s-dropbox.yaml
    flags:
      apply: ["--prune", "-l", "project=services"]
